// export const GET_CREATIVES = "GET_CREATIVES";
export const TOGGLE_SIDENAV = "TOGGLE_SIDENAV";
export const TOGGLE_SEARCH = "TOGGLE_SEARCH";
export const TOGGLE_MESSAGES = "TOGGLE_MESSAGES";
export const TOGGLE_PROFILE_DROPDOWN = "TOGGLE_PROFILE_DROPDOWN";
export const SEARCH_TEXT = "SEARCH_TEXT";
export const CLEAR_SEARCH = "CLEAR_SEARCH";
